# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jan-Benedikt Jagusch
title: Data Scientist, Python Software Engineer and Open Source Fan
email: jan.jagusch@gmail.com
website: https://janjagusch.github.io/

# Social links
twitter_username: jan_jagusch
github_username:  janjagusch
linkedin_username: janjagusch
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Jan and I want to make a data scientist's life easier!
  I am currently working as data science teadmlead at [Instaffo](https://instaffo.com/) in Heidelberg, Germany. I am also a [PyData Südwest](https://www.meetup.com/PyData-Suedwest/) organizer.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
